-- MySQL Workbench Synchronization
-- Generated: 2019-08-20 11:58
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: digio

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';




ALTER TABLE `admin` 
DROP COLUMN `admin_id`,
CHANGE COLUMN `user_fk_user_id` `admin_fk_user_id` INT(11) NOT NULL FIRST,
CHANGE COLUMN `admin_type` `admin_type` VARCHAR(45) NULL DEFAULT 'normal' ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`admin_fk_user_id`);
;

ALTER TABLE `admin` 
ADD CONSTRAINT `fk_admin_user1`
  FOREIGN KEY (`admin_fk_user_id`)
  REFERENCES `user` (`user_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
