-- MySQL Workbench Synchronization
-- Generated: 2019-08-23 13:59
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: digio

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `leaders` 
CHANGE COLUMN `leaders_quote` `leaders_quote` TEXT(1000) NULL DEFAULT NULL COMMENT 'Thsi table will contains the leaders of various ministries\\n' ;

ALTER TABLE `admin` 
ADD COLUMN `admin_registered_by` VARCHAR(255) NULL DEFAULT NULL AFTER `admin_type`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
