-- MySQL Workbench Synchronization
-- Generated: 2019-08-29 17:33
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: digio

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `cudb`.`article_comments` 
ADD COLUMN `parent_comment_id` INT(11) NOT NULL AFTER `article_comments_fk_user_id`,
ADD COLUMN `article_comment_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `parent_comment_id`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
