-- MySQL Workbench Synchronization
-- Generated: 2019-08-19 16:48
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: digio

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `user` 
ADD COLUMN `user_course` VARCHAR(500) NULL DEFAULT NULL AFTER `user_regno`,
CHANGE COLUMN `user_id` `user_id` INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `user_img` `user_img` VARCHAR(255) NULL DEFAULT 0 ;

ALTER TABLE `article` 
CHANGE COLUMN `article_edit_date` `article_edit_date` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP ,
CHANGE COLUMN `article_status` `article_status` TINYINT(4) NULL DEFAULT 0 ;

ALTER TABLE `leaders` 
CHANGE COLUMN `leaders_quote` `leaders_quote` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Thsi table will contains the leaders of various ministries\n' ;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
